executor: KubernetesExecutor

dags:
  gitSync:
    enabled: true
    repo: https://github.com/AkelloVJ/kubernetes.git
    branch: main  # Optional: specify the branch if not the default one
    rev: HEAD     # Syncs the latest commit from the main branch
    depth: 1
    # Adding GIT_SYNC_SUBPATH environment variable to point to the specific path in the repo
    env: 
      - name: GIT_SYNC_SUBPATH
        value: "Data engineering/dags"  # Subpath where the DAGs are located within the repo

# Encryption and webserver keys
airflow:
  fernetKey: ZDBTWXQ1RGtOWXN5T1V6ZmRMWXh3RTQ0Qm5yQ2pRdFI=

secretKey: ZDBTWXQ1RGtOWXN5T1V6ZmRMWXh3RTQ0Qm5yQ2pRdFI=
