fernetKey: ZDBTWXQ1RGtOWXN5T1V6ZmRMWXh3RTQ0Qm5yQ2pRdFI=
secretKey: ZDBTWXQ1RGtOWXN5T1V6ZmRMWXh3RTQ0Qm5yQ2pRdFI=
executor: KubernetesExecutor
webserverSecretKey: 4820162d42b84f726cd78ce1d2cef4b4

dags:
  gitSync:
    enabled: true
    repo: https://github.com/AkelloVJ/kubernetes.git
    branch: main  # Optional: specify the branch if not the default one
    rev: HEAD     # Syncs the latest commit from the main branch
    depth: 1
    maxFailures: 0
    subPath: "dags"  # Subpath where the DAGs are located within the repo

